# apiVersion: v1
# kind: Service
# metadata:
#   name: gitea-ngrok
#   namespace: default
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 3000
#   selector:
#     app: gitea
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gitea-ngrok
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: gitea-ngrok
#   template:
#     metadata:
#       labels:
#         app: gitea-ngrok
#     spec:
#       containers:
#         - name: ngrok
#           image: wernight/ngrok
#           args: ["http", "gitea-http.default.svc.cluster.local:8000", "--log=stdout"]



---
- name: Expose Gitea via Ngrok
  hosts: localhost
  tasks:
    - name: Ensure Ngrok is installed
      command: which ngrok
      register: ngrok_installed
      ignore_errors: true

    - name: Download and install Ngrok if not present
      when: ngrok_installed.rc != 0
      block:
        - name: Download Ngrok
          get_url:
            url: "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip"
            dest: "/tmp/ngrok.zip"

        - name: Unzip Ngrok
          unarchive:
            src: "/tmp/ngrok.zip"
            dest: "/usr/local/bin/"
            remote_src: yes

        - name: Verify Ngrok Installation
          command: ngrok version

    - name: Start Ngrok Tunnel for Gitea
      command: ngrok http 3000
      async: 3600
      poll: 0
      register: ngrok_output

    - name: Display Instructions
      debug:
        msg: |
          Ngrok is running! Check the terminal for the public URL.
          Alternatively, visit: http://localhost:4040/status to see the active tunnel.
